version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
sphinx:
  # Path to the shared conf.py file.
  configuration: docs/source/source/conf.py
  fail_on_warning: false  # 暂时禁用警告失败

python:
  install:
    - requirements: requirements.txt


sphinx:
  fail_on_warning: true

formats: all

